Prevent logging unnecessarily in production environments
octokit/request-error.js pull request #252
Opened 2022-08-11 01:35 UTC by dfrankland

It's not productive to warn about deprecations, especially only once, in production environments. To prevent unnecessary logging, check the `process.env.NODE_ENV` which idiomatically is set in production environments.

2022-08-11 19:33 UTC, gr2m commented on src/index.ts
> +  if (process.env.NODE_ENV !== "production") {
we cannot introduce Node-specific APIs, this is a universal library

2022-08-11 19:34 UTC, gr2m requested changes
we cannot introduce Node-specific APIs, this is a universal library

2023-05-26 12:17 UTC, till commented
I would also like to see this land. =)

2023-05-26 20:19 UTC, gr2m commented
Sorry this pull request as is, is a no-go, as I said: we cannot introduce Node-specific APIs, this is a universal library.

The problem with deprecation messages are there so you address them either in your code or by upgrading your dependencies.

2023-05-26 20:19 UTC, closed without merging

2023-05-26 21:29 UTC, till commented
@gr2m I understand, but as I said on the other ticket (the one with the monkey patch): I installed it only yesterday or two days ago. The option is to upgrade to ...?

Not telling you to release faster, but do you understand the annoyance from the user end?

2023-05-26 21:43 UTC, gr2m commented
What is the code that results in the deprecation message?

2023-05-27 16:49 UTC, till commented
> What is the code that results in the deprecation message?

Anything that triggers an error.

I was listing issues from a repo with state and tag filter and e.g. forgot to add the correct token or had incorrect permissions. Then it "barfs". 😄

2023-05-27 22:29 UTC, gr2m commented
> Anything that triggers an error.

That shouldn't be the case, not if you use the latest Octokit libraries. Unless you try to access `error.headers` or `error.code`, but then you can fix it in your code.

2023-05-30 16:23 UTC, till commented
Here are my direct dependencies:

```
    "@octokit/core": "^4.2.1",
    "@octokit/rest": "^19.0.11"
```

It's whatever I installed at the time (a week ago?).

I am not using `error` myself. I just try/catch and display an error message myself.